version: '3.1'

services:
  web:
    container_name: drupal
    image: drupal
    ports:
      - 80:80
    volumes:
      - drupal-data:/var/www/html
    restart: always

  db:
    container_name: postgres
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_USER: $DB_USER
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  drupal-data: