<<<<<<< HEAD
version: '3.1'
=======
version: '2'
>>>>>>> dd40c9d (edit: ghost compose)

services:

  ghost:
    image: ghost:4-alpine
    restart: always
    ports:
      - 8080:2368
<<<<<<< HEAD
=======
    depends_on:
      db:
        condition: service_healthy
>>>>>>> dd40c9d (edit: ghost compose)
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: $DB_USER
      database__connection__password: $DB_PASS
      database__connection__database: $DB_NAME
      # this url value is just an example, and is likely wrong for your environment!
      url: http://$URL:8080
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      #NODE_ENV: development

  db:
    image: mysql:8.0
    restart: always
    environment:
<<<<<<< HEAD
      MYSQL_ROOT_PASSWORD: $DB_PASS
=======
      MYSQL_ROOT_PASSWORD: $DB_PASS
      MYSQL_PASSWORD: $DB_PASS
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
    ports:
      - "127.0.0.1:3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -P 3306 -p$DB_PASS | grep 'mysqld is alive' || exit 1"]
      interval: 2s
      retries: 15
>>>>>>> dd40c9d (edit: ghost compose)
