version: '3.6'
services:
  web:
    container_name: gitlab
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    environment:
      GITLAB_ROOT_PASSWORD: $WEB_PASS
      GITLAB_OMNIBUS_CONFIG: |
        external_url '$URL'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ~/gitlab/config:/etc/gitlab'
      - ~/gitlab/logs:/var/log/gitlab'
      - ~/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'