version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: $DB_PASS
      MARIADB_DATABASE: $DB_NAME

  adminer:
    image: adminer
    restart: always
    ports:
      - 80:8080