version: '3.1'

services:

  db:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: $DB_NAME
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASS
    volumes:
      - mongodb-data:/data/db

  web:
    container_name: mongo_express
    image: mongo-express
    restart: always
    ports:
      - 80:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: $WEB_USER
      ME_CONFIG_BASICAUTH_PASSWORD: $WEB_PASS
      ME_CONFIG_MONGODB_ADMINUSERNAME: $DB_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $DB_PASS
      ME_CONFIG_MONGODB_URL: mongodb://$DB_USER:$DB_PASS@mongo:27017/

volumes:
  mongodb-data: