version: '3.1'

services:
  db:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASS
      MYSQL_USER: $DB_USER
      MYSQL_DATABASE: $DB_NAME
      MYSQL_PASSWORD: $DB_PASS
    volumes:
      - mysql-data:/var/lib/mysql
  web:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 80:8080

volumes:
  mysql-data: