version: '2'

services:
  web:
    container_name: nextcloud
    image: nextcloud
    restart: always
    ports:
      - 80:80
    environment:
      MYSQL_HOST=db
      MYSQL_PASSWORD=$DB_PASS
      MYSQL_DATABASE=nextcloud
      MYSQL_USER=nextcloud
    volumes:
      - nextcloud:/var/www/html

  db:
    container_name: mariadb
    image: mariadb:10.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASS
      - MYSQL_PASSWORD=$DB_PASS
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

volumes:
  nextcloud:
  db: