version: '3.1'

services:

  web:
    container_name: odoo
    image: odoo:14.0
    depends_on:
      - mydb
    ports:
      - "80:8069"
    environment:
      HOST: mydb
      USER: $DB_USER
      PASSWORD: $DB_PASS
  mydb:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS