version: '3.1'

services:
  web:
    container_name: odoo
    image: odoo:14.0
    ports:
      - "80:8069"
    environment:
      HOST: db
      USER: $DB_USER
      PASSWORD: $DB_PASS
    volumes:
      - odoo-data:/var/lib/odoo
  db:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  odoo-data:
  postgres-data: