version: '3.1'

services:

  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 80:8080