# Testing GitHub codespace

version: '3.1'

services:

  wordpress:
    container_name: wordpress
    image: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: 'DB_USER'
      WORDPRESS_DB_PASSWORD: 'DB_PASS'
      WORDPRESS_DB_NAME: 'DB_NAME'
    volumes:
      - wordpress:/var/www/html

  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'DB_NAME'
      MYSQL_USER: 'DB_USER'
      MYSQL_PASSWORD: 'DB_PASS'
      MYSQL_RANDOM_ROOT_PASSWORD: 'DB_ROOT_PASS'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
